package com.haseltonmediagroup.coverartvideomaker

import android.content.ContentValues
import android.graphics.*
import android.media.*
import android.net.Uri
import android.os.Bundle
import android.provider.MediaStore
import android.widget.*
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AppCompatActivity

class MainActivity:AppCompatActivity(){
 private var artUri:Uri?=null;private var audioUri:Uri?=null;private lateinit var status:TextView;private lateinit var createButton:Button;private lateinit var preset:Spinner
 private val artPicker=registerForActivityResult(ActivityResultContracts.GetContent()){if(it!=null){artUri=it;status.text="Cover art selected";ready()}}
 private val audioPicker=registerForActivityResult(ActivityResultContracts.GetContent()){if(it!=null){audioUri=it;status.text="Audio selected";ready()}}
 override fun onCreate(b:Bundle?){super.onCreate(b);val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(40,70,40,40);setBackgroundColor(Color.rgb(17,19,24))};root.addView(label("COVER ART VIDEO MAKER",25f));root.addView(label("Turn your artwork + song into an MP4 — entirely on your phone.",15f));root.addView(Button(this).apply{text="SELECT COVER ART";setOnClickListener{artPicker.launch("image/*")}});root.addView(Button(this).apply{text="SELECT AUDIO";setOnClickListener{audioPicker.launch("audio/*")}});preset=Spinner(this).apply{adapter=ArrayAdapter(this@MainActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("YouTube 1920 × 1080","Square 1080 × 1080","Vertical 1080 × 1920"))};root.addView(preset);createButton=Button(this).apply{text="CREATE MP4";isEnabled=false;setOnClickListener{startRender()}};root.addView(createButton);status=label("Choose cover art and audio to begin.",14f);root.addView(status);setContentView(root)}
 private fun label(v:String,s:Float)=TextView(this).apply{text=v;textSize=s;setTextColor(Color.WHITE);setPadding(0,12,0,12)}
 private fun ready(){createButton.isEnabled=artUri!=null&&audioUri!=null};private fun progress(v:String){runOnUiThread{status.text=v}}
 private fun startRender(){createButton.isEnabled=false;progress("Preparing media… 5%");Thread{try{render()}catch(e:Exception){runOnUiThread{status.text="Render failed: ${e.message}";createButton.isEnabled=true}}}.start()}
 private fun draw(surface:android.view.Surface,b:Bitmap,w:Int,h:Int,p:Paint){val c=surface.lockCanvas(null);try{c.drawColor(Color.BLACK);val s=minOf(w.toFloat()/b.width,h.toFloat()/b.height);val dw=b.width*s;val dh=b.height*s;c.drawBitmap(b,null,RectF((w-dw)/2,(h-dh)/2,(w+dw)/2,(h+dh)/2),p)}finally{surface.unlockCanvasAndPost(c)}}
 private fun render(){val art=artUri?:error("No art");val audio=audioUri?:error("No audio");val(w,h)=arrayOf(1920 to 1080,1080 to 1080,1080 to 1920)[preset.selectedItemPosition];val mmr=MediaMetadataRetriever();mmr.setDataSource(this,audio);val durationUs=(mmr.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION)?.toLongOrNull()?:error("No duration"))*1000;mmr.release();val bitmap=contentResolver.openInputStream(art).use{requireNotNull(BitmapFactory.decodeStream(it))};val name="CoverArtVideo_${System.currentTimeMillis()}.mp4";val cv=ContentValues().apply{put(MediaStore.Video.Media.DISPLAY_NAME,name);put(MediaStore.Video.Media.MIME_TYPE,"video/mp4");put(MediaStore.Video.Media.RELATIVE_PATH,"Movies/Cover Art Video Maker")};val out=contentResolver.insert(MediaStore.Video.Media.EXTERNAL_CONTENT_URI,cv)?:error("Output failed");val ofd=contentResolver.openFileDescriptor(out,"w")?:error("Output open failed");val mux=MediaMuxer(ofd.fileDescriptor,MediaMuxer.OutputFormat.MUXER_OUTPUT_MPEG_4)
  val vf=MediaFormat.createVideoFormat(MediaFormat.MIMETYPE_VIDEO_AVC,w,h).apply{setInteger(MediaFormat.KEY_COLOR_FORMAT,MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface);setInteger(MediaFormat.KEY_BIT_RATE,4_000_000);setInteger(MediaFormat.KEY_FRAME_RATE,1);setInteger(MediaFormat.KEY_I_FRAME_INTERVAL,5)};val ve=MediaCodec.createEncoderByType(MediaFormat.MIMETYPE_VIDEO_AVC);ve.configure(vf,null,null,MediaCodec.CONFIGURE_FLAG_ENCODE);val surface=ve.createInputSurface();ve.start();val vi=MediaCodec.BufferInfo();var vt=-1
  val af=MediaFormat.createAudioFormat(MediaFormat.MIMETYPE_AUDIO_AAC,44100,2).apply{setInteger(MediaFormat.KEY_AAC_PROFILE,MediaCodecInfo.CodecProfileLevel.AACObjectLC);setInteger(MediaFormat.KEY_BIT_RATE,192000)};val ae=MediaCodec.createEncoderByType(MediaFormat.MIMETYPE_AUDIO_AAC);ae.configure(af,null,null,MediaCodec.CONFIGURE_FLAG_ENCODE);ae.start();val ai=MediaCodec.BufferInfo();var at=-1;val paint=Paint(Paint.ANTI_ALIAS_FLAG or Paint.FILTER_BITMAP_FLAG);draw(surface,bitmap,w,h,paint);val seed=ae.dequeueInputBuffer(10000);if(seed>=0)ae.queueInputBuffer(seed,0,0,0,0);repeat(200){if(vt<0){val x=ve.dequeueOutputBuffer(vi,10000);if(x==MediaCodec.INFO_OUTPUT_FORMAT_CHANGED)vt=mux.addTrack(ve.outputFormat)else if(x>=0)ve.releaseOutputBuffer(x,false)};if(at<0){val x=ae.dequeueOutputBuffer(ai,10000);if(x==MediaCodec.INFO_OUTPUT_FORMAT_CHANGED)at=mux.addTrack(ae.outputFormat)else if(x>=0)ae.releaseOutputBuffer(x,false)};if(vt>=0&&at>=0)return@repeat};require(vt>=0&&at>=0){"Encoder init failed"};mux.start();progress("Creating cover video… 30%");val total=(durationUs+999999)/1000000;for(sec in 0..total){draw(surface,bitmap,w,h,paint);drain(ve,mux,vt,vi,false);if(sec%10L==0L)progress("Creating cover video… ${30+((sec.coerceAtMost(total)*20)/total.coerceAtLeast(1)).toInt()}%")};ve.signalEndOfInputStream();drain(ve,mux,vt,vi,true);progress("Converting audio to AAC… 55%");transcode(audio,ae,mux,at,durationUs);progress("Finalizing… 95%");ve.stop();ve.release();surface.release();ae.stop();ae.release();mux.stop();mux.release();ofd.close();bitmap.recycle();runOnUiThread{status.text="Complete — saved to Movies/Cover Art Video Maker/$name";createButton.isEnabled=true;Toast.makeText(this,"MP4 created",Toast.LENGTH_LONG).show()}}
 private fun drain(enc:MediaCodec,mux:MediaMuxer,track:Int,info:MediaCodec.BufferInfo,end:Boolean){var idle=0;while(true){val x=enc.dequeueOutputBuffer(info,if(end)10000 else 0);if(x==MediaCodec.INFO_TRY_AGAIN_LATER){if(!end)return;if(++idle>100)error("Encoder timeout")}else if(x>=0){idle=0;val b=enc.getOutputBuffer(x);if(b!=null&&info.size>0){b.position(info.offset);b.limit(info.offset+info.size);mux.writeSampleData(track,b,info)};val eos=info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM!=0;enc.releaseOutputBuffer(x,false);if(eos)return}}}
 private fun transcode(uri:Uri,enc:MediaCodec,mux:MediaMuxer,track:Int,durationUs:Long){val ex=MediaExtractor();val fd=contentResolver.openFileDescriptor(uri,"r")?:error("Audio open failed");ex.setDataSource(fd.fileDescriptor);var idx=-1;for(i in 0 until ex.trackCount)if(ex.getTrackFormat(i).getString(MediaFormat.KEY_MIME)?.startsWith("audio/")==true){idx=i;break};require(idx>=0);ex.selectTrack(idx);val fmt=ex.getTrackFormat(idx);val mime=fmt.getString(MediaFormat.KEY_MIME)?:error("Audio format missing");val dec=MediaCodec.createDecoderByType(mime);dec.configure(fmt,null,null,0);dec.start();val di=MediaCodec.BufferInfo();val ei=MediaCodec.BufferInfo();var extractorDone=false;var decoderDone=false;var encoderDone=false;var pending:ByteArray?=null;var pendingPos=0;var pendingPts=0L;var lastPct=-1;var idle=0
  while(!encoderDone){var moved=false
   while(true){val ox=enc.dequeueOutputBuffer(ei,0);if(ox>=0){val ob=enc.getOutputBuffer(ox);if(ob!=null&&ei.size>0){ob.position(ei.offset);ob.limit(ei.offset+ei.size);mux.writeSampleData(track,ob,ei)};encoderDone=ei.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM!=0;enc.releaseOutputBuffer(ox,false);moved=true}else break}
   if(pending!=null){val ix=enc.dequeueInputBuffer(0);if(ix>=0){val ib=enc.getInputBuffer(ix)!!;ib.clear();val data=pending!!;val n=minOf(ib.remaining(),data.size-pendingPos);ib.put(data,pendingPos,n);enc.queueInputBuffer(ix,0,n,pendingPts,0);pendingPos+=n;if(pendingPos>=data.size){pending=null;pendingPos=0};moved=true}}
   if(pending==null&&!decoderDone){val ox=dec.dequeueOutputBuffer(di,0);if(ox>=0){if(di.size>0){val db=dec.getOutputBuffer(ox)!!;db.position(di.offset);db.limit(di.offset+di.size);pending=ByteArray(di.size);db.get(pending!!);pendingPts=di.presentationTimeUs;val pct=55+((pendingPts.coerceAtLeast(0)*35)/durationUs.coerceAtLeast(1)).toInt().coerceIn(0,35);if(pct!=lastPct){lastPct=pct;progress("Converting audio to AAC… $pct%")}};decoderDone=di.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM!=0;dec.releaseOutputBuffer(ox,false);moved=true}}
   if(!extractorDone){val ix=dec.dequeueInputBuffer(0);if(ix>=0){val ib=dec.getInputBuffer(ix)!!;val n=ex.readSampleData(ib,0);if(n<0){dec.queueInputBuffer(ix,0,0,0,MediaCodec.BUFFER_FLAG_END_OF_STREAM);extractorDone=true}else{dec.queueInputBuffer(ix,0,n,ex.sampleTime,0);ex.advance()};moved=true}}
   if(decoderDone&&pending==null){val ix=enc.dequeueInputBuffer(0);if(ix>=0){enc.queueInputBuffer(ix,0,0,durationUs,MediaCodec.BUFFER_FLAG_END_OF_STREAM);decoderDone=false;moved=true}}
   if(moved)idle=0 else{Thread.sleep(2);if(++idle>15000)error("Audio pipeline timed out")}
  };dec.stop();dec.release();ex.release();fd.close()}
}
